### ISSUE TITLE
Fails to load with paperMC

### ISSUE THREAD

**Issue by wmantly** [gigabit101/Shrink#56]
```
[20:24:55 INFO]: This server is running Paper version git-Paper-384 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 51b7b60)
...
[20:24:56 ERROR]: Could not load 'plugins/Shrink-1.17.1-1.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[patched_1.17.1.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:158) ~[patched_1.17.1.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-384]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-384]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
```

**Comment by gigabit101** [comment]
This is a mod that requires Minecraft forge not a plug-in
